title: Joseph Choe
email: joseph@josephchoe.com
description: >-
  I think about software development, writing, and many other things.
baseurl: ""
url: https://josephchoe.com
twitter_username: josephchoe
github_username:  josephchoe
image_url: /assets/images/zurrey.jpg

# Build settings
source: _app
destination: _site
markdown: kramdown
highlighter: rouge
# theme: minima
# plugins:
#   - jekyll-feed
include:
  - _pages

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      permalink: /:basename
  - scope:
      path: "_posts"
      type: posts
    values:
      permalink: :year/:month/:day/:title
      category: blog
  - scope:
      path: "_posts/article"
      type: posts
    values:
      permalink: article/:title
      category: article
  - scope:
      path: "_posts/writing"
      type: posts
    values:
      permalink: writing/:title
      category: writing

# Markdown settings
kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  syntax_highlighter_opts:
    css_class:               "highlight"
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"
