title: Joseph Choe
email: joseph@josephchoe.com
description: >-
  I think about software development, writing, and many other things.
baseurl: ""
url: https://josephchoe.com
twitter_username: josephchoe
github_username:  josephchoe
image_url: /assets/images/zurrey.jpg

# Fallbacks for display
author_name:
author_site:

# Copyright
copyright_date: 2000-01-01
copyright_holder: Joseph Choe

# Build settings
source: _app
destination: _site
markdown: kramdown
highlighter: rouge
# theme: minima
plugins:
#   - jekyll-feed
  - jekyll-last-modified-at
include:
  - _pages

defaults:
  - scope:
      path: "_pages/index.html"
    values:
      is_index: true
  - scope:
      path: "_pages"
      type: pages
    values:
      permalink: /:basename
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      permalink: :year/:month/:day/:title
      category: log
  - scope:
      path: "_posts/essay"
      type: posts
    values:
      layout: essay
      permalink: /:title
      category: essay
  - scope:
      path: "_posts/fiction"
      type: posts
    values:
      layout: fiction
      permalink: /:title
      category: fiction
  - scope:
      path: "_posts/video"
      type: posts
    values:
      layout: video
      permalink: /:title
      category: video

# Markdown settings
kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  syntax_highlighter_opts:
    css_class:               "highlight"
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"
